#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=45 blur_radius=0 color=$BAR_COLOR hidden=false

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=-10
  icon.font="FiraCode Nerd Font Mono:Bold:17.0"
  label.font="FiraCode Nerd Font Mono:Bold:17.0"
  #icon.color=$ACCENT_COLOR
  #label.color=$ACCENT_COLOR
  background.color=$ITEM_BG_COLOR
  background.corner_radius=0
  background.height=25
  icon.padding_left=5
  icon.padding_right=0
  label.padding_left=0
  label.padding_right=5
  background.drawing=on
  background.border_color=$BORDER_COLOR
  background.border_width=1
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
#source $ITEM_DIR/front_app.sh

# -- Right Side Items --
#source $ITEM_DIR/cpu.sh
#source $ITEM_DIR/battery.sh
source $ITEM_DIR/calendar.sh



##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
